### ISSUE TITLE
Badchars still bad

### ISSUE THREAD

**Issue by C-Sto** [EgeBalci/sgn#6]
Hi,

There is a bug in the way that badchars are identified:
https://github.com/EgeBalci/sgn/blob/980093296b90e4c0a5c944c51189f761c9de729f/main.go#L101-L105

the `range` operator returns an iterable _index_, not the value at the index, and the `continue` keyword breaks out of the inner `range` loop, not the outer loop. So when a badchar is identified (which will just be a number counting from 0 to however many badchars were in the parameter, not the actual badchar), the program drops out and into the 'write file, everything is good' part, even though it still has badchars.

When I fixed this, it took an *extremely* long time to brute force a single badchar (null) on a reasonably large shellcode blob. I suspect that removing/altering badchars may need to be a separate deliberate encoding step, rather than hoping that sgn just happens to not have the character in the output.

**Comment by EgeBalci** [comment]
Hi,
Thanks a lot for reporting this. I was also planning to improve the bad character removal approach now it became a milestone in the [project](https://github.com/EgeBalci/sgn/projects/1). I have pushed a temporary fix until I come up with a better way. According to my tests brute force approach works on most of the cases but for some bytes the chance is very low because of the  frequently used instructions inside the decoder stub. And unfortunately the `\x00` (null) is one of them.  `¯\_( ͡° ͜ʖ ͡°)_/¯`
